airflow_db:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: dbt
      threads: 4

jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: jf67392.europe-west4.gcp
      
      user: dbt_user
      password: dbt_password
      
      role: dbt_dev_role
      database: dbt_hol_dev
      warehouse: dbt_dev_wh
      schema: public
      threads: 200
    prod:
      type: snowflake
      account: jf67392.europe-west4.gcp
      
      user: dbt_user
      password: dbt_password
      
      role: dbt_prod_role
      database: dbt_hol_prod
      warehouse: dbt_prod_wh
      schema: public
      threads: 200